apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bindery-core.fullname" . }}-manager-role
  labels:
    {{- include "bindery-core.labels" . | nindent 4 }}
rules:
  - apiGroups: ["bindery.platform"]
    resources: ["modulemanifests", "booklets", "worldinstances", "worldshards", "worldstorageclaims", "capabilitybindings", "realms", "shardautoscalers", "capabilitydefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["bindery.platform"]
    resources: ["worldshards", "worldstorageclaims", "capabilitybindings", "realms", "shardautoscalers"]
    verbs: ["create", "update", "patch", "delete"]
  - apiGroups: ["bindery.platform"]
    resources: ["capabilitybindings/status", "worldinstances/status", "worldshards/status", "worldstorageclaims/status", "realms/status", "shardautoscalers/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bindery-core.fullname" . }}-manager-rolebinding
  labels:
    {{- include "bindery-core.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bindery-core.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "bindery-core.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}
