apiVersion: bindery.platform/v1alpha1
kind: WorldInstance
metadata:
  name: bindery-sample-world
  namespace: bindery-demo
spec:
  gameRef:
    name: bindery-sample
  worldId: world-001
  region: us-test-1
  shardCount: 2
  desiredState: Running
